"""organization channels and quote approval tokens

Revision ID: 0178740628f3
Revises: 27ee109b82b3
Create Date: 2026-09-12 14:46:26.030242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0178740628f3'
down_revision: Union[str, None] = '27ee109b82b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('channel_value', sa.String(length=320), nullable=False),
    sa.Column('provider_sid', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_channels_channel_value'), 'organization_channels', ['channel_value'], unique=True)
    op.create_index(op.f('ix_organization_channels_organization_id'), 'organization_channels', ['organization_id'], unique=False)
    op.add_column('quotes', sa.Column('approval_token_hash', sa.String(length=64), nullable=True))
    op.add_column('quotes', sa.Column('approval_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('quotes', sa.Column('approval_revoked_at', sa.DateTime(), nullable=True))
    op.add_column('quotes', sa.Column('approved_via', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_quotes_approval_token_hash'), 'quotes', ['approval_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_approval_token_hash'), table_name='quotes')
    op.drop_column('quotes', 'approved_via')
    op.drop_column('quotes', 'approval_revoked_at')
    op.drop_column('quotes', 'approval_token_expires_at')
    op.drop_column('quotes', 'approval_token_hash')
    op.drop_index(op.f('ix_organization_channels_organization_id'), table_name='organization_channels')
    op.drop_index(op.f('ix_organization_channels_channel_value'), table_name='organization_channels')
    op.drop_table('organization_channels')
    # ### end Alembic commands ###
