"""suppliers catalog job requirements assignments order status

Revision ID: 27ee109b82b3
Revises: 7fd632c4f305
Create Date: 2026-09-12 10:53:06.873310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27ee109b82b3'
down_revision: Union[str, None] = '7fd632c4f305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('catalog_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_catalog_items_organization_id'), 'catalog_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_sku'), 'catalog_items', ['sku'], unique=False)
    op.create_index(op.f('ix_catalog_items_supplier_id'), 'catalog_items', ['supplier_id'], unique=False)
    op.create_table('job_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_rates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_assignments_job_id'), 'job_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_organization_id'), 'job_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_user_id'), 'job_assignments', ['user_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('workers_needed', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_job_id'), 'job_requirements', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_requirements_organization_id'), 'job_requirements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_job_requirements_skill_id'), 'job_requirements', ['skill_id'], unique=False)
    # material_orders gains supplier_id + status; batch mode so SQLite works,
    # server_default so existing rows get a valid status.
    with op.batch_alter_table('material_orders') as batch:
        batch.add_column(sa.Column('supplier_id', sa.String(length=36), nullable=True))
        batch.add_column(sa.Column('status', sa.String(length=32), nullable=False,
                                   server_default='draft'))
        batch.create_index(op.f('ix_material_orders_status'), ['status'], unique=False)
        batch.create_index(op.f('ix_material_orders_supplier_id'), ['supplier_id'], unique=False)
        batch.create_foreign_key('fk_material_orders_supplier', 'suppliers',
                                 ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_orders') as batch:
        batch.drop_constraint('fk_material_orders_supplier', type_='foreignkey')
        batch.drop_index(op.f('ix_material_orders_supplier_id'))
        batch.drop_index(op.f('ix_material_orders_status'))
        batch.drop_column('status')
        batch.drop_column('supplier_id')
    op.drop_index(op.f('ix_job_requirements_skill_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_organization_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_job_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_job_assignments_user_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_organization_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_job_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_catalog_items_supplier_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_sku'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_organization_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
